### ISSUE TITLE
Ability to change vc-typing-indicator timeout for stop-typing

### ISSUE THREAD

**Issue by iujielim** [nexmo-community/clientsdk-ui-js#8]
In current setting, the timeout for stop-typing is a fixed value. It will be great if there is an attribute to control the timeout.

**Comment by conshus** [comment]
Hi @iujielim. Just added "typingTimeout" property to https://github.com/nexmo-community/clientsdk-ui-js/tree/main/vc-text-input

Give it a try and let us know what you think. Thanks.
